### ISSUE TITLE
Project Summary / Description

### ISSUE THREAD

**Issue by diegosouza** [cooltrick/git2docker.io#2]
Hello,

Your project seems to be interesting, but I think it lacks summary/description.
It starts with some commands how to set up, but, what's the focus? Is it to fill what needs? What are the current limitations or planned features? (supposing it is new as the commit dates)

**Comment by ralvares** [comment]
Hello Diego Souza.

I'm doing the summary/description and I will commit the new read-me file and new features soon.
The focus is just simplify the Deploy using Dockerfile or Code detection. I just started the project because any friends had not permission to install or run other tools like heroku or flynn cli to deploy or manage containers. They just have a IDE and a GIT client, with git2docker is possible to deploy and manage Containers in a local standalone server, and of course learn more about Go programing.

**Comment by diegosouza** [comment]
Ok, thanks for answering my question.
Since you're doing the summary I think it can be closed.
